spring:
  application:
    name: ecommerce

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  profiles:
    include: oauth, jwt, redis, email, aws

